config/routes.rb
Rails.application.routes.draw do
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :games do
  	resources :reviews
  end
  root 'games#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :games
end

app/models/game.rb
class Game < ApplicationRecord

	belongs_to :user
	belongs_to :category
	has_many :reviews
	has_attached_file :game_img, styles: { game_index: "250x350>", game_show: "320x480>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :game_img, content_type: /\Aimage\/.*\Z/

end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :game
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	has_many :games
	has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
	before_action :find_game, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, only: [:new, :edit]
	def index
		if params[:category].blank?
			@games = Game.all.order("created_at DESC")
		else
			@category_id = Category.find_by(name: params[:category]).id
			@games = Game.where(:category_id => @category_id).order("created_at DESC")
		end
	end

	def new
		@game = current_user.games.build
		@categories = Category.all.map{|c| [c.name, c.id]}
	end

	def show
		if @game.reviews.blank?
			@average_review = 0
		else
			@average_review = @game.reviews.average(:rating).round(2)
		end
	end

	def create
		@game = current_user.games.build(game_params)
		@game.category_id = params[:category_id]
		if @game.save
			redirect_to root_path
		else
			render 'new'
		end
	end

	def edit
		@categories = Category.all.map{|c| [c.name, c.id]}
	end

	def update
		@game.category_id = params[:category_id]
		if @game.update(game_params)
			redirect_to game_path(@game)
		else
			render 'edit'
		end
	end

	def destroy
		@game.destroy
		redirect_to root_path
	end
		

	private
	def game_params
		params.require(:game).permit(:title,:description,:developer,:category_id,:game_img,:download,:video)
	end

	def find_game
		@game = Game.find(params[:id])
	end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :find_game
	before_action :find_review, only: [:edit, :update, :destroy]
	before_action :authenticate_user!, only: [:new, :edit]
	def new
		@review = Review.new
	end

	def create
		@review = Review.new(review_params)
		@review.game_id = @game.id
		@review.user_id = current_user.id
		if @review.save
			redirect_to game_path(@game)
		else
			render "new"
		end
	end

	def edit

	end

	def update
		@review = Review.find(params[:id])
		if @review.update(review_params)
			redirect_to game_path(@game)
		else
			render 'edit'
		end
	end

	def destroy
		@review.destroy
		redirect_to game_path(@game)
	end

	private
		def review_params
			params.require(:review).permit(:rating, :comment)
		end

		def find_game
			@game = Game.find(params[:game_id])
		end

		def find_review
			@review = Review.find(params[:id])
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/games/_form.html.erb
<%= simple_form_for @game, :html => { :multipart => true }  do |f| %>
	<%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select a category") %>
	<%= f.file_field :game_img %>
	<%= f.input :title, label: "Game Title" %>
	<%= f.input :description %>
	<%= f.input :developer %>
	<%= f.input :download %>
	<%= f.input :video %>
	<%= f.button :submit, class: "btn-custom2" %>
<% end %>

app/views/games/edit.html.erb
<div class='col-md-6 col-md-offset-3'>
	<div class='new-game-form'>

	<h1>Edit Game</h1>

	<%= simple_form_for @game, :html => { :multipart => true } do |f| %>
		<%= f.select :category_id, @categories %>
		<%= f.file_field :game_img %>
		<%= f.input :title, label: "Game Title" %>
		<%= f.input :description %>
		<%= f.input :developer %>
		<%= f.input :download %>
		<%= f.input :video %>
		<%= f.button :submit, class: 'btn-custom2' %>
	<% end %>

	</div>

</div>

app/views/games/index.html.erb
<h1 class='current-category'><%= params[:category] %></h1>

<% if @games.count == 0 %>
	<h1>There are no game in this category </h1>

<% else %>

	<div class="row">
	<% @games.each do |game| %>
		<div class="col-md-3">
			<p class='title'><%= game.title %></p>
			<a href="/games/<%= game.id %>">
				<%= image_tag game.game_img.url(:game_index), class: "game" %>
				</a>
		</div>
	<% end %>
	</div>
<% end %>

app/views/games/new.html.erb
<div class='col-md-6 col-md-offset-3'>
	<div class='new-game-form'>

		<h3>New Game</h3>

		<%= render 'form' %>
		
	</div>
</div>

app/views/games/show.html.erb
<div class="row">
	<div class="col-md-4">
	<%= image_tag @game.game_img.url(:game_show), class: "game-show" %>

	<%= video_tag("#{@game.video}", size:'320x180', controls: true, autobuffer: true ) %>

		<div class="link btn-group">
		<%= link_to "Back", root_path, class: 'btn btn-custom' %>

		<% if user_signed_in? %>

			<% if @game.user_id == current_user.id %>

				<%= link_to "Edit", edit_game_path(@game), class: 'btn btn-custom' %>
				<%= link_to "Delete", game_path(@game), method: :delete, data: {confirm: "Are You Sure?"}, class: 'btn btn-custom' %>
			<% end %>

		<% end %>
		</div>
	</div>
	<div class="col-md-8">

		<div class="game-info">
			<h2 class='game-title'><%= @game.title %></h2>
			<h3 class='game-developer'>Developer: <%= @game.developer %></h3>
			<h3 class='game-download'>Download Link: <%= link_to @game.download, "http://#{@game.download}", target: "_blank" %></h3>
			<h2 class='avg-rating'>Average Rating</h2>
			<div class="average-review-rating" data-score=<%= @average_review %>></div>
			<span class='number-of-reviews'>Based on <%= @game.reviews.count %> reviews</span>
			<p class='game-description'>Description: <%= @game.description %></p>
		</div>

			<div class='reviews'>
			<!-- review section -->
			<h1>Reviews</h1>
			<%= render @game.reviews %>
			<div>
				<%= link_to "Add Review", new_game_review_path(@game) %>
			</div>
		</div>
	</div>
</div>



<script>
$('.review-rating').raty({
	readOnly: true,
	score: function() {
		return $(this).attr('data-score');
	},
	path: '/assets'
});

</script>

<script>
$('.average-review-rating').raty({
	readOnly: true,
	path: '/assets',
	score: function() {
		return $(this).attr('data-score');
	}
});

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GameDB</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <%= image_tag("gamespot.png", size:'48x48', alt:'gamedb_logo') %>
          <%= link_to "GameDB", root_path, class:"navbar-brand" %>

        </div>

      <ul class='nav navbar-nav navbar-right'>
        <li><%= link_to "Sign Up", new_admin_user_path %></li>

        <% if user_signed_in? %>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
          <% else %>
          <li><%= link_to "Log In", new_user_session_path %>
        <% end %>
      </ul>

      <ul class="nav navbar-nav navbar-right">

        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expandable="false">Category <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
                <% Category.all.each do |category| %>
                    <li class="<%= 'active' if params[:category] == category.name %>">
                    <%= link_to category.name, games_path(category: category.name, class:"link") %>
                    </li>
                <% end %>
            </ul>  
        </li>

        <% if user_signed_in? %>
          <li><%= link_to "Add Game", new_game_path, class: 'btn btn-custom' %></li>
          <% end %>

      </ul>

      </div>

    </nav>


       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <div class="container">
       <%= yield %>
    </div>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= simple_form_for([@game, @game.reviews.build]) do |f| %>
	<div id="rating-form">
		<label>Rating</label>
	</div>
	<%= f.input :comment %>
	<%= f.button :submit, class: 'btn-custom2' %>
<% end %>

<script>
	$('#rating-form').raty({
		path: '/assets',
		scoreName: 'review[rating]'
	});
</script>

app/views/reviews/_review.html.erb
<div class="review" >

	<div class="review-rating" data-score="<%= review.rating %>"></div>
	<p><%= review.comment %></p>

	<% if user_signed_in? %>
		<% if review.user_id == current_user.id %>
			<div class="links btn-group">

			<%= link_to "Edit", edit_game_review_path(review.game, review), class: "btn btn-custom" %>
			<%= link_to "Delete", game_review_path(review.game, review), method: :delete, data: { confirm: "Are You Sure?"}, class: "btn btn-custom" %>

			<% end %>

	<% end %>

</div>

app/views/reviews/edit.html.erb
<div class='col-md-6 col-md-offset-3'>
	<div class='new-game-form'>

	<h1>Edit Review</h1>

	<%= simple_form_for([@game, @review]) do |f| %>
		<div id="rating-form">
			<label>Rating</label>
		</div>
		<%= f.input :comment %>
		<%= f.button :submit, class: "btn-custom2" %>
	<% end %>

	</div>

</div>

<script>
	$('#rating-form').raty({
		path: '/assets',
		scoreName: 'review[rating]'
	});
</script>

app/views/reviews/new.html.erb
<div class='col-md-6 col-md-offset-3'>
	<div class='new-game-form'>

		<h1>New Review</h1>

		<%= render "form" %>

	</div>

</div>